Repository NicolasT/troupe, pull requests merged in 2023-03, with the labels that each got.

#21 troupe: add thread affinity to SpawnOptions
  troupe/src/Troupe.hs
  troupe/src/Troupe/Process.hs
  troupe/test/Troupe/Test.hs
  troupe/troupe.cabal
Labels: enhancement

#7 First implementation bits (long-running PR)
  .github/workflows/codestyle.yml
  .github/workflows/haskell-ci.yml
  cabal.haskell-ci
  cabal.project
  troupe/.hlint.yaml
  troupe/src/MyLib.hs
  troupe/src/Troupe.hs
  troupe/src/Troupe/Exceptions.hs
  troupe/src/Troupe/Process.hs
  troupe/src/Troupe/Types.hs
  troupe/test/Main.hs
  troupe/test/Troupe/Test.hs
  troupe/test/troupe-test.hs
  troupe/troupe-distributed-process/Control/Distributed/Process/Internal/CQueue.hs
  troupe/troupe-distributed-process/Control/Distributed/Process/Internal/StrictList.hs
  troupe/troupe-distributed-process/Control/Distributed/Process/Internal/StrictMVar.hs
  troupe/troupe.cabal
Labels: help wanted

#31 troupe: "allow" processes to catch signals
  troupe/src/Troupe/Process.hs
  troupe/test/Troupe/Test.hs
Labels: bug

#33 test: fix test for #30
  troupe/test/Troupe/Test.hs
Labels: bug

#37 troupe: move non-primitive actions out of `Process`
  troupe/src/Troupe.hs
  troupe/src/Troupe/Process.hs
Labels: good first issue
